version: "3"

services:

  database:
    image : mysql

    ports:
      - 3306:3306

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tododb
      MYSQL_USER: todouser
      MYSQL_PASSWORD: todopass

    volumes:
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d
